// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package anypb

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Any
func (this *Any) MarshalJSON() ([]byte, error) {
	str, err := AnyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Any
func (this *Any) UnmarshalJSON(b []byte) error {
	return AnyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	AnyMarshaler   = &jsonpb.Marshaler{}
	AnyUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
