// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package durationpb

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Duration
func (this *Duration) MarshalJSON() ([]byte, error) {
	str, err := DurationMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Duration
func (this *Duration) UnmarshalJSON(b []byte) error {
	return DurationUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	DurationMarshaler   = &jsonpb.Marshaler{}
	DurationUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
