// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package emptypb

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Empty
func (this *Empty) MarshalJSON() ([]byte, error) {
	str, err := EmptyMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Empty
func (this *Empty) UnmarshalJSON(b []byte) error {
	return EmptyUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	EmptyMarshaler   = &jsonpb.Marshaler{}
	EmptyUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
