// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package structpb

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Struct
func (this *Struct) MarshalJSON() ([]byte, error) {
	str, err := StructMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Struct
func (this *Struct) UnmarshalJSON(b []byte) error {
	return StructUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Value
func (this *Value) MarshalJSON() ([]byte, error) {
	str, err := StructMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Value
func (this *Value) UnmarshalJSON(b []byte) error {
	return StructUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListValue
func (this *ListValue) MarshalJSON() ([]byte, error) {
	str, err := StructMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListValue
func (this *ListValue) UnmarshalJSON(b []byte) error {
	return StructUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	StructMarshaler   = &jsonpb.Marshaler{}
	StructUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
