// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package timestamppb

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for Timestamp
func (this *Timestamp) MarshalJSON() ([]byte, error) {
	str, err := TimestampMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Timestamp
func (this *Timestamp) UnmarshalJSON(b []byte) error {
	return TimestampUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	TimestampMarshaler   = &jsonpb.Marshaler{}
	TimestampUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
