// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package wrapperspb

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for DoubleValue
func (this *DoubleValue) MarshalJSON() ([]byte, error) {
	str, err := WrappersMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DoubleValue
func (this *DoubleValue) UnmarshalJSON(b []byte) error {
	return WrappersUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for FloatValue
func (this *FloatValue) MarshalJSON() ([]byte, error) {
	str, err := WrappersMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for FloatValue
func (this *FloatValue) UnmarshalJSON(b []byte) error {
	return WrappersUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Int64Value
func (this *Int64Value) MarshalJSON() ([]byte, error) {
	str, err := WrappersMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Int64Value
func (this *Int64Value) UnmarshalJSON(b []byte) error {
	return WrappersUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for UInt64Value
func (this *UInt64Value) MarshalJSON() ([]byte, error) {
	str, err := WrappersMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for UInt64Value
func (this *UInt64Value) UnmarshalJSON(b []byte) error {
	return WrappersUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Int32Value
func (this *Int32Value) MarshalJSON() ([]byte, error) {
	str, err := WrappersMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Int32Value
func (this *Int32Value) UnmarshalJSON(b []byte) error {
	return WrappersUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for UInt32Value
func (this *UInt32Value) MarshalJSON() ([]byte, error) {
	str, err := WrappersMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for UInt32Value
func (this *UInt32Value) UnmarshalJSON(b []byte) error {
	return WrappersUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BoolValue
func (this *BoolValue) MarshalJSON() ([]byte, error) {
	str, err := WrappersMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BoolValue
func (this *BoolValue) UnmarshalJSON(b []byte) error {
	return WrappersUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for StringValue
func (this *StringValue) MarshalJSON() ([]byte, error) {
	str, err := WrappersMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for StringValue
func (this *StringValue) UnmarshalJSON(b []byte) error {
	return WrappersUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BytesValue
func (this *BytesValue) MarshalJSON() ([]byte, error) {
	str, err := WrappersMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BytesValue
func (this *BytesValue) UnmarshalJSON(b []byte) error {
	return WrappersUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	WrappersMarshaler   = &jsonpb.Marshaler{}
	WrappersUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
