// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for IstioCertificateRequest
func (this *IstioCertificateRequest) MarshalJSON() ([]byte, error) {
	str, err := CitadelMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IstioCertificateRequest
func (this *IstioCertificateRequest) UnmarshalJSON(b []byte) error {
	return CitadelUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for IstioCertificateResponse
func (this *IstioCertificateResponse) MarshalJSON() ([]byte, error) {
	str, err := CitadelMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IstioCertificateResponse
func (this *IstioCertificateResponse) UnmarshalJSON(b []byte) error {
	return CitadelUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CitadelMarshaler   = &jsonpb.Marshaler{}
	CitadelUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
