// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package ext_procv3

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for ProtocolConfiguration
func (this *ProtocolConfiguration) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ProtocolConfiguration
func (this *ProtocolConfiguration) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ProcessingRequest
func (this *ProcessingRequest) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ProcessingRequest
func (this *ProcessingRequest) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ProcessingResponse
func (this *ProcessingResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ProcessingResponse
func (this *ProcessingResponse) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HttpHeaders
func (this *HttpHeaders) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HttpHeaders
func (this *HttpHeaders) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HttpBody
func (this *HttpBody) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HttpBody
func (this *HttpBody) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HttpTrailers
func (this *HttpTrailers) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HttpTrailers
func (this *HttpTrailers) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeadersResponse
func (this *HeadersResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeadersResponse
func (this *HeadersResponse) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for TrailersResponse
func (this *TrailersResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for TrailersResponse
func (this *TrailersResponse) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BodyResponse
func (this *BodyResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BodyResponse
func (this *BodyResponse) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CommonResponse
func (this *CommonResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CommonResponse
func (this *CommonResponse) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ImmediateResponse
func (this *ImmediateResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ImmediateResponse
func (this *ImmediateResponse) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GrpcStatus
func (this *GrpcStatus) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GrpcStatus
func (this *GrpcStatus) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderMutation
func (this *HeaderMutation) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderMutation
func (this *HeaderMutation) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BodyMutation
func (this *BodyMutation) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BodyMutation
func (this *BodyMutation) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for StreamedBodyResponse
func (this *StreamedBodyResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for StreamedBodyResponse
func (this *StreamedBodyResponse) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderMap
func (this *HeaderMap) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderMap
func (this *HeaderMap) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderValue
func (this *HeaderValue) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderValue
func (this *HeaderValue) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HttpStatus
func (this *HttpStatus) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HttpStatus
func (this *HttpStatus) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderValueOption
func (this *HeaderValueOption) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderValueOption
func (this *HeaderValueOption) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ProcessingMode
func (this *ProcessingMode) MarshalJSON() ([]byte, error) {
	str, err := ExtProcMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ProcessingMode
func (this *ProcessingMode) UnmarshalJSON(b []byte) error {
	return ExtProcUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ExtProcMarshaler   = &jsonpb.Marshaler{}
	ExtProcUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
