// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package authv3

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for CheckRequest
func (this *CheckRequest) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CheckRequest
func (this *CheckRequest) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for DeniedHttpResponse
func (this *DeniedHttpResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for DeniedHttpResponse
func (this *DeniedHttpResponse) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for OkHttpResponse
func (this *OkHttpResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for OkHttpResponse
func (this *OkHttpResponse) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CheckResponse
func (this *CheckResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CheckResponse
func (this *CheckResponse) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Status
func (this *Status) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Status
func (this *Status) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AttributeContext
func (this *AttributeContext) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AttributeContext
func (this *AttributeContext) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AttributeContext_Peer
func (this *AttributeContext_Peer) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AttributeContext_Peer
func (this *AttributeContext_Peer) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AttributeContext_Request
func (this *AttributeContext_Request) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AttributeContext_Request
func (this *AttributeContext_Request) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AttributeContext_HttpRequest
func (this *AttributeContext_HttpRequest) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AttributeContext_HttpRequest
func (this *AttributeContext_HttpRequest) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AttributeContext_TLSSession
func (this *AttributeContext_TLSSession) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AttributeContext_TLSSession
func (this *AttributeContext_TLSSession) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HttpStatus
func (this *HttpStatus) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HttpStatus
func (this *HttpStatus) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderValueOption
func (this *HeaderValueOption) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderValueOption
func (this *HeaderValueOption) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderValue
func (this *HeaderValue) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderValue
func (this *HeaderValue) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for QueryParameter
func (this *QueryParameter) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for QueryParameter
func (this *QueryParameter) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Address
func (this *Address) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Address
func (this *Address) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for SocketAddress
func (this *SocketAddress) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for SocketAddress
func (this *SocketAddress) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Metadata
func (this *Metadata) MarshalJSON() ([]byte, error) {
	str, err := ExtAuthzMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Metadata
func (this *Metadata) UnmarshalJSON(b []byte) error {
	return ExtAuthzUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ExtAuthzMarshaler   = &jsonpb.Marshaler{}
	ExtAuthzUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
