// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package ratelimitv3

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for RateLimitRequest
func (this *RateLimitRequest) MarshalJSON() ([]byte, error) {
	str, err := RlsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitRequest
func (this *RateLimitRequest) UnmarshalJSON(b []byte) error {
	return RlsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitResponse
func (this *RateLimitResponse) MarshalJSON() ([]byte, error) {
	str, err := RlsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitResponse
func (this *RateLimitResponse) UnmarshalJSON(b []byte) error {
	return RlsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitResponse_RateLimit
func (this *RateLimitResponse_RateLimit) MarshalJSON() ([]byte, error) {
	str, err := RlsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitResponse_RateLimit
func (this *RateLimitResponse_RateLimit) UnmarshalJSON(b []byte) error {
	return RlsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitResponse_Quota
func (this *RateLimitResponse_Quota) MarshalJSON() ([]byte, error) {
	str, err := RlsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitResponse_Quota
func (this *RateLimitResponse_Quota) UnmarshalJSON(b []byte) error {
	return RlsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitResponse_DescriptorStatus
func (this *RateLimitResponse_DescriptorStatus) MarshalJSON() ([]byte, error) {
	str, err := RlsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitResponse_DescriptorStatus
func (this *RateLimitResponse_DescriptorStatus) UnmarshalJSON(b []byte) error {
	return RlsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderValue
func (this *HeaderValue) MarshalJSON() ([]byte, error) {
	str, err := RlsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderValue
func (this *HeaderValue) UnmarshalJSON(b []byte) error {
	return RlsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitDescriptor
func (this *RateLimitDescriptor) MarshalJSON() ([]byte, error) {
	str, err := RlsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitDescriptor
func (this *RateLimitDescriptor) UnmarshalJSON(b []byte) error {
	return RlsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitDescriptor_Entry
func (this *RateLimitDescriptor_Entry) MarshalJSON() ([]byte, error) {
	str, err := RlsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitDescriptor_Entry
func (this *RateLimitDescriptor_Entry) UnmarshalJSON(b []byte) error {
	return RlsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for RateLimitDescriptor_RateLimitOverride
func (this *RateLimitDescriptor_RateLimitOverride) MarshalJSON() ([]byte, error) {
	str, err := RlsMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for RateLimitDescriptor_RateLimitOverride
func (this *RateLimitDescriptor_RateLimitOverride) UnmarshalJSON(b []byte) error {
	return RlsUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	RlsMarshaler   = &jsonpb.Marshaler{}
	RlsUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
